export const SCALE_UP = 'SCALE_UP'
export const SCALE_NORMAL = 'SCALE_NORMAL'

export const INIT_MATCHES_LENGTH = 'INIT_MATCHES_LENGTH'
export const FETCH_MATCH = 'FETCH_MATCH'
export const INIT_BRACKET = 'INIT_BRACKET'
